# Use an official Node.js image as a base image
FROM node

# Create a working directory inside the container
WORKDIR /Users/ruslanmoiseyenko/Desktop/Programming/automation_course/playwright/tests-examples

# Run a simple command
CMD ["echo", "123"]
